export interface Song {
  id: string;
  title: string;
  artist: string;
  coverUrl: string;
  voteCount: number;
  previewUrl?: string; // Optional audio preview
}

export interface DailyWinner extends Song {
  date: string;
  vibeDescription?: string; // Generated by Gemini
}

export enum AppView {
  HOME = 'HOME',
  VOTE = 'VOTE',
  PLAYLIST = 'PLAYLIST'
}

export type VoteStatus = 'idle' | 'signing' | 'confirming' | 'success' | 'error';

// Web3 Types
export interface TransactionReceipt {
  to: string;
  from: string;
  status: boolean;
  hash: string;
}